export type QuestionLevel = 'junior' | 'middle' | 'senior'

export interface BankQuestion {
  id: string
  category: string
  level: QuestionLevel
  ua: string
  en: string
}

// Recruiter (Easy) — Junior: General + Linux fundamentals.
export const RECRUITER_QUESTIONS: BankQuestion[] = [
  { id: 'j-general-1', category: 'general', level: 'junior', ua: 'Що таке DevOps?', en: 'What is DevOps?' },
  {
    id: 'j-general-2',
    category: 'general',
    level: 'junior',
    ua: 'Ви набираєте google.com у браузері. Розкажіть якомога детальніше, що відбувається в цей час?',
    en: 'You type google.com in a browser. Describe in as much detail as possible what happens next.',
  },
  { id: 'j-general-3', category: 'general', level: 'junior', ua: 'Як працює HTTPS?', en: 'How does HTTPS work?' },
  {
    id: 'j-general-4',
    category: 'general',
    level: 'junior',
    ua: 'Поясніть концепцію Infrastructure as Code, для чого це потрібно і які проблеми вирішує?',
    en: 'Explain the concept of Infrastructure as Code — why is it needed and what problems does it solve?',
  },
  {
    id: 'j-linux-5',
    category: 'linux',
    level: 'junior',
    ua: 'Опишіть загальну архітектуру операційної системи.',
    en: 'Describe the general architecture of an operating system.',
  },
  {
    id: 'j-linux-6',
    category: 'linux',
    level: 'junior',
    ua: 'Опишіть основне призначення операційної системи.',
    en: 'Describe the main purpose of an operating system.',
  },
  {
    id: 'j-linux-7',
    category: 'linux',
    level: 'junior',
    ua: 'Навіщо потрібні файлові системи? Які існують?',
    en: 'Why are file systems needed? Which ones exist?',
  },
  {
    id: 'j-linux-8',
    category: 'linux',
    level: 'junior',
    ua: 'У чому різниця між віртуалізацією і контейнеризацією?',
    en: 'What is the difference between virtualization and containerization?',
  },
  {
    id: 'j-linux-9',
    category: 'linux',
    level: 'junior',
    ua: 'У чому переваги контейнерів?',
    en: 'What are the advantages of containers?',
  },
  {
    id: 'j-linux-10',
    category: 'linux',
    level: 'junior',
    ua: 'Яка файлова структура у Linux (UNIX) систем, що розташовані в /etc, /dev, /proc, /sys, /lib, /var (кілька директорій на вибір)?',
    en: "What is the Linux (UNIX) filesystem layout — what's in /etc, /dev, /proc, /sys, /lib, /var (pick a few)?",
  },
  { id: 'j-linux-11', category: 'linux', level: 'junior', ua: 'Що таке Load Average?', en: 'What is Load Average?' },
  {
    id: 'j-linux-12',
    category: 'linux',
    level: 'junior',
    ua: 'У чому різниця між soft та hard symlink?',
    en: 'What is the difference between a soft and a hard symlink?',
  },
  {
    id: 'j-linux-13',
    category: 'linux',
    level: 'junior',
    ua: 'Як працюють file permissions, навіщо директорії права виконання (+x)?',
    en: 'How do file permissions work, and why does a directory need the execute (+x) permission?',
  },
  { id: 'j-linux-14', category: 'linux', level: 'junior', ua: 'Що таке zombie process?', en: 'What is a zombie process?' },
  {
    id: 'j-linux-15',
    category: 'linux',
    level: 'junior',
    ua: 'За допомогою чого можна зібрати інформацію про поточний стан процесора, пам\'яті, диска, мережі?',
    en: 'What can you use to gather information about the current state of the CPU, memory, disk, and network?',
  },
  { id: 'j-linux-16', category: 'linux', level: 'junior', ua: 'Що таке swappiness?', en: 'What is swappiness?' },
  {
    id: 'j-linux-17',
    category: 'linux',
    level: 'junior',
    ua: 'Як подивитися вільне місце на диску?',
    en: 'How do you check free disk space?',
  },
  { id: 'j-linux-18', category: 'linux', level: 'junior', ua: 'Що таке inode?', en: 'What is an inode?' },
  {
    id: 'j-linux-19',
    category: 'linux',
    level: 'junior',
    ua: 'Розкажіть поетапно процес завантаження Linux від моменту ввімкнення живлення комп\'ютера.',
    en: 'Describe step by step the Linux boot process from the moment the computer is powered on.',
  },
  {
    id: 'j-linux-20',
    category: 'linux',
    level: 'junior',
    ua: 'Що станеться під час виконання команд: 1. cat file1 > file2; 2. cat file1 >> file2?',
    en: 'What happens when you run these commands: 1. cat file1 > file2; 2. cat file1 >> file2?',
  },
  {
    id: 'j-linux-21',
    category: 'linux',
    level: 'junior',
    ua: 'У чому різниця між Ctrl+C та Ctrl+Z?',
    en: "What's the difference between Ctrl+C and Ctrl+Z?",
  },
  {
    id: 'j-linux-22',
    category: 'linux',
    level: 'junior',
    ua: 'Як перенаправити одночасно stderr та stdin?',
    en: 'How do you redirect stderr and stdin at the same time?',
  },
  {
    id: 'j-linux-23',
    category: 'linux',
    level: 'junior',
    ua: 'Як вбити процес? Які є типи сигналів?',
    en: 'How do you kill a process? What signal types exist?',
  },
  { id: 'j-linux-24', category: 'linux', level: 'junior', ua: 'Що робить команда grep?', en: 'What does the grep command do?' },
  { id: 'j-linux-25', category: 'linux', level: 'junior', ua: 'Що таке скрипт bash?', en: 'What is a bash script?' },
  {
    id: 'j-linux-26',
    category: 'linux',
    level: 'junior',
    ua: 'Які типи змінних використовують у bash?',
    en: 'What variable types are used in bash?',
  },
  {
    id: 'j-linux-27',
    category: 'linux',
    level: 'junior',
    ua: 'Що виведуть команди: 1. echo ${hostname}; 2. echo $(hostname);',
    en: 'What will these commands print: 1. echo ${hostname}; 2. echo $(hostname);',
  },
]

// HR (Medium) — the rest of Junior: Networks, Clouds, Automation, Security,
// Virtualization, CI/CD, Development, Monitoring/Logging, Practical.
export const HR_QUESTIONS: BankQuestion[] = [
  {
    id: 'j-networks-28',
    category: 'networks',
    level: 'junior',
    ua: 'Що таке модель OSI, TCP/IP?',
    en: 'What is the OSI model? TCP/IP?',
  },
  {
    id: 'j-networks-29',
    category: 'networks',
    level: 'junior',
    ua: 'Для чого потрібні network masks?',
    en: 'What are network masks for?',
  },
  {
    id: 'j-networks-30',
    category: 'networks',
    level: 'junior',
    ua: 'Структура IP-пакета. З чого складається? Що таке фрагментація та чому вона відбувається?',
    en: 'IP packet structure — what does it consist of? What is fragmentation and why does it happen?',
  },
  {
    id: 'j-networks-31',
    category: 'networks',
    level: 'junior',
    ua: 'Що таке колізія? Чому виникає?',
    en: 'What is a network collision? Why does it occur?',
  },
  { id: 'j-networks-32', category: 'networks', level: 'junior', ua: 'Що таке проксі?', en: 'What is a proxy?' },
  {
    id: 'j-networks-33',
    category: 'networks',
    level: 'junior',
    ua: 'Що таке firewalls і навіщо вони потрібні?',
    en: 'What are firewalls and why are they needed?',
  },
  {
    id: 'j-networks-34',
    category: 'networks',
    level: 'junior',
    ua: 'Що таке NAT і навіщо він потрібен?',
    en: 'What is NAT and why is it needed?',
  },
  {
    id: 'j-networks-35',
    category: 'networks',
    level: 'junior',
    ua: 'Які типи IP-адрес ви знаєте?',
    en: 'What types of IP addresses do you know?',
  },
  {
    id: 'j-networks-36',
    category: 'networks',
    level: 'junior',
    ua: 'За яким портом і протоколом працюють Ping і Traceroute?',
    en: 'What port and protocol do Ping and Traceroute use?',
  },
  {
    id: 'j-clouds-37',
    category: 'clouds',
    level: 'junior',
    ua: 'У чому різниця між IaaS, PaaS та SaaS?',
    en: "What's the difference between IaaS, PaaS, and SaaS?",
  },
  {
    id: 'j-clouds-38',
    category: 'clouds',
    level: 'junior',
    ua: 'Що таке VPC і з яких компонентів має складатись?',
    en: 'What is a VPC and what components should it consist of?',
  },
  {
    id: 'j-clouds-39',
    category: 'clouds',
    level: 'junior',
    ua: 'Що таке cloud-init? init/systemd/upstart configs?',
    en: 'What is cloud-init? init/systemd/upstart configs?',
  },
  { id: 'j-automation-40', category: 'automation', level: 'junior', ua: 'Що таке IaaC і навіщо він потрібний?', en: 'What is IaC and why is it needed?' },
  { id: 'j-automation-41', category: 'automation', level: 'junior', ua: 'Що таке Terraform?', en: 'What is Terraform?' },
  {
    id: 'j-automation-42',
    category: 'automation',
    level: 'junior',
    ua: 'Які інструменти автоматизації ви знаєте?',
    en: 'What automation tools do you know?',
  },
  {
    id: 'j-security-43',
    category: 'security',
    level: 'junior',
    ua: 'У чому різниця між аутентифікацією та авторизацією?',
    en: "What's the difference between authentication and authorization?",
  },
  {
    id: 'j-security-44',
    category: 'security',
    level: 'junior',
    ua: 'Сертифікати. Як працює HTTPS? Що таке certificate ciphers?',
    en: 'Certificates. How does HTTPS work? What are certificate ciphers?',
  },
  {
    id: 'j-security-45',
    category: 'security',
    level: 'junior',
    ua: 'Як безпечно передати дані своєму колезі?',
    en: 'How do you securely share data with a colleague?',
  },
  { id: 'j-security-46', category: 'security', level: 'junior', ua: 'Що таке MFA, TOTP?', en: 'What is MFA, TOTP?' },
  {
    id: 'j-virtualization-47',
    category: 'virtualization',
    level: 'junior',
    ua: 'У чому різниця між віртуалізацією та контейнеризацією? У чому плюси та мінуси?',
    en: "What's the difference between virtualization and containerization? Pros and cons?",
  },
  {
    id: 'j-virtualization-48',
    category: 'virtualization',
    level: 'junior',
    ua: 'Як для при запуску Docker-контейнера «повісити» його з 80-го порту в контейнері на 8081 на хост?',
    en: "How do you map a Docker container's port 80 to host port 8081 at container start?",
  },
  {
    id: 'j-virtualization-49',
    category: 'virtualization',
    level: 'junior',
    ua: 'Як передати у віртуальну машину USB device?',
    en: 'How do you pass a USB device into a virtual machine?',
  },
  {
    id: 'j-virtualization-50',
    category: 'virtualization',
    level: 'junior',
    ua: 'Docker-контейнер споживає багато SWAP. Що робити?',
    en: 'A Docker container is consuming a lot of SWAP. What do you do?',
  },
  {
    id: 'j-cicd-51',
    category: 'ci-cd',
    level: 'junior',
    ua: 'Що таке Continuous Integration та Continuous Deployment? У чому різниця між Continuous Deployment і Continuous Delivery?',
    en: 'What are Continuous Integration and Continuous Deployment? What is the difference between Continuous Deployment and Continuous Delivery?',
  },
  { id: 'j-cicd-52', category: 'ci-cd', level: 'junior', ua: 'Опишіть основні етапи CI/CD.', en: 'Describe the main stages of CI/CD.' },
  {
    id: 'j-cicd-53',
    category: 'ci-cd',
    level: 'junior',
    ua: 'Опишіть приклад процесу CI (та/або CD), який починається з моменту, коли розробник запушив зміни/PR до Git?',
    en: 'Describe an example CI (and/or CD) process starting from the moment a developer pushes changes/a PR to Git.',
  },
  {
    id: 'j-cicd-54',
    category: 'ci-cd',
    level: 'junior',
    ua: 'Розкажіть про різновиди тестів, які ми можемо використовувати в CI пайплайні.',
    en: 'Describe the kinds of tests you can use in a CI pipeline.',
  },
  {
    id: 'j-cicd-55',
    category: 'ci-cd',
    level: 'junior',
    ua: 'Які інструменти CI ви використовували? Чи є досвід роботи з Jenkinsfile?',
    en: 'What CI tools have you used? Do you have experience with a Jenkinsfile?',
  },
  {
    id: 'j-cicd-56',
    category: 'ci-cd',
    level: 'junior',
    ua: 'Які види тестів ви знаєте і навіщо вони потрібні?',
    en: 'What types of tests do you know and why are they needed?',
  },
  {
    id: 'j-development-57',
    category: 'development',
    level: 'junior',
    ua: 'Git. Як вирішити merge conflict? Що таке rebase, cherry-pick?',
    en: 'Git. How do you resolve a merge conflict? What are rebase and cherry-pick?',
  },
  {
    id: 'j-development-58',
    category: 'development',
    level: 'junior',
    ua: 'У чому різниця між git merge та git rebase?',
    en: "What's the difference between git merge and git rebase?",
  },
  { id: 'j-development-59', category: 'development', level: 'junior', ua: 'Які UI використовували?', en: 'Which Git UIs have you used?' },
  {
    id: 'j-development-60',
    category: 'development',
    level: 'junior',
    ua: 'Яка різниця між GitLab/GitHub/Bitbucket?',
    en: "What's the difference between GitLab/GitHub/Bitbucket?",
  },
  {
    id: 'j-development-61',
    category: 'development',
    level: 'junior',
    ua: 'Яка різниця між Git pull/Git fetch?',
    en: "What's the difference between git pull and git fetch?",
  },
  { id: 'j-development-62', category: 'development', level: 'junior', ua: 'Що таке Git-flow?', en: 'What is Git-flow?' },
  {
    id: 'j-development-63',
    category: 'development',
    level: 'junior',
    ua: 'Версіонування. Яка різниця між SemVer та CalVer?',
    en: "Versioning. What's the difference between SemVer and CalVer?",
  },
  {
    id: 'j-development-64',
    category: 'development',
    level: 'junior',
    ua: 'Тестування. Які існують види? Як писати тести, TDD?',
    en: 'Testing. What kinds exist? How do you write tests, TDD?',
  },
  {
    id: 'j-development-65',
    category: 'development',
    level: 'junior',
    ua: 'У чому різниця між компільованими та інтерпретаційними мовами програмування?',
    en: "What's the difference between compiled and interpreted programming languages?",
  },
  {
    id: 'j-monitoring-66',
    category: 'monitoring',
    level: 'junior',
    ua: 'Які метрики треба збирати? Різниця між infrastructure та application monitoring.',
    en: 'Which metrics should be collected? The difference between infrastructure and application monitoring.',
  },
  {
    id: 'j-monitoring-67',
    category: 'monitoring',
    level: 'junior',
    ua: 'Яка різниця між pull та push model у системах моніторингу?',
    en: "What's the difference between the pull and push model in monitoring systems?",
  },
  {
    id: 'j-monitoring-68',
    category: 'monitoring',
    level: 'junior',
    ua: 'Яка різниця між Black box та White box monitoring?',
    en: "What's the difference between black-box and white-box monitoring?",
  },
  {
    id: 'j-monitoring-69',
    category: 'monitoring',
    level: 'junior',
    ua: 'Розкажіть про підходи до збору application логів.',
    en: 'Describe approaches to collecting application logs.',
  },
  {
    id: 'j-practical-71',
    category: 'practical',
    level: 'junior',
    ua: 'Напишіть просту програму мовою на ваш вибір. Програма має отримувати повідомлення з сервісу черг і друкувати його в stdout. Сервіс черг — на ваш розсуд.',
    en: 'Write a simple program in a language of your choice. It should receive a message from a queue service and print it to stdout. Pick any queue service.',
  },
  {
    id: 'j-practical-72',
    category: 'practical',
    level: 'junior',
    ua: 'Розберіть структуру сервісу (на прикладі Docker-compose).',
    en: 'Break down the structure of a service (using a docker-compose example).',
  },
  {
    id: 'j-practical-73',
    category: 'practical',
    level: 'junior',
    ua: 'Практична сесія роботи з Git (Git command line: fetch, push, pull, rebase, checkout, submodules).',
    en: 'A practical Git session (command line: fetch, push, pull, rebase, checkout, submodules).',
  },
]

// Senior DevOps (Hard) — all Middle-level questions.
export const SENIOR_DEVOPS_QUESTIONS: BankQuestion[] = [
  { id: 'm-linux-1', category: 'linux', level: 'middle', ua: 'Опишіть архітектуру ядра Linux.', en: 'Describe the Linux kernel architecture.' },
  { id: 'm-linux-2', category: 'linux', level: 'middle', ua: 'Що таке ядро ​​і яке його призначення?', en: 'What is the kernel and what is its purpose?' },
  {
    id: 'm-linux-3',
    category: 'linux',
    level: 'middle',
    ua: 'Опишіть загальні частини файлової системи Unix/Linux, архітектуру файлової системи.',
    en: 'Describe the general parts of the Unix/Linux filesystem and its architecture.',
  },
  { id: 'm-linux-4', category: 'linux', level: 'middle', ua: 'У чому різниця між RedHat і Debian?', en: "What's the difference between RedHat and Debian?" },
  { id: 'm-linux-5', category: 'linux', level: 'middle', ua: 'У чому різниця між /proc and /sys?', en: "What's the difference between /proc and /sys?" },
  {
    id: 'm-linux-6',
    category: 'linux',
    level: 'middle',
    ua: 'Ситуація: показує, що на диску зайнято 50% місця, а створити файл навіть під root користувачем не можемо. У чому проблема?',
    en: "Scenario: disk usage shows 50% used, yet even root can't create a file. What's the problem?",
  },
  {
    id: 'm-linux-7',
    category: 'linux',
    level: 'middle',
    ua: 'Ми видалили файл, який відкрив застосунок. Як нам його відновити?',
    en: 'We deleted a file that an application still has open. How do we recover it?',
  },
  {
    id: 'm-linux-8',
    category: 'linux',
    level: 'middle',
    ua: 'Як знайти PID процесу, його стартові параметри?',
    en: "How do you find a process's PID and its startup parameters?",
  },
  {
    id: 'm-linux-9',
    category: 'linux',
    level: 'middle',
    ua: 'Як перевірити, чи відкритий порт на віддаленому хості, локальному хості?',
    en: 'How do you check whether a port is open on a remote host / local host?',
  },
  { id: 'm-linux-10', category: 'linux', level: 'middle', ua: 'Як шукати файл за його вмістом?', en: 'How do you search for a file by its content?' },
  {
    id: 'm-linux-11',
    category: 'linux',
    level: 'middle',
    ua: 'Що таке SSH, як організувати доступ на сервер без пароля або з певних хостів? Як обмежити доступні для виконання команди?',
    en: 'What is SSH — how do you set up passwordless access or access limited to specific hosts? How do you restrict which commands can be run?',
  },
  {
    id: 'm-linux-12',
    category: 'linux',
    level: 'middle',
    ua: 'Як перевірити спожиті ресурси під час сеансу SSH?',
    en: 'How do you check resources consumed during an SSH session?',
  },
  { id: 'm-linux-13', category: 'linux', level: 'middle', ua: 'Що означає дозвіл на файл 755?', en: 'What does file permission 755 mean?' },
  { id: 'm-linux-14', category: 'linux', level: 'middle', ua: 'Що таке SELinux і навіщо він потрібен?', en: 'What is SELinux and why is it needed?' },
  {
    id: 'm-linux-15',
    category: 'linux',
    level: 'middle',
    ua: 'Як визначити PCI-пристрій у системі, наприклад RAID controller?',
    en: 'How do you identify a PCI device in the system, e.g. a RAID controller?',
  },
  {
    id: 'm-linux-16',
    category: 'linux',
    level: 'middle',
    ua: 'Як перейменувати пристрій, наприклад мережеву карту чи диск?',
    en: 'How do you rename a device, e.g. a network card or disk?',
  },
  {
    id: 'm-linux-17',
    category: 'linux',
    level: 'middle',
    ua: 'Що таке LVM? Які знаєте приклади використання?',
    en: 'What is LVM? What use cases do you know?',
  },
  { id: 'm-linux-18', category: 'linux', level: 'middle', ua: 'Що таке root reserved space?', en: 'What is root reserved space?' },
  { id: 'm-linux-19', category: 'linux', level: 'middle', ua: 'Що таке exit code та як його дізнатися?', en: 'What is an exit code and how do you find it out?' },
  {
    id: 'm-linux-20',
    category: 'linux',
    level: 'middle',
    ua: 'Чому вивід df -h показує, що на диску зайнято мало місця, але система не дає записати файл із повідомленням no space left on device?',
    en: 'Why does `df -h` show little disk space used, yet the system refuses to write a file with "no space left on device"?',
  },
  {
    id: 'm-linux-21',
    category: 'linux',
    level: 'middle',
    ua: 'У чому різниця між command1 & command2 та command1 && command2, а також command1 && command2 || command3?',
    en: "What's the difference between `command1 & command2` vs `command1 && command2`, and `command1 && command2 || command3`?",
  },
  {
    id: 'm-linux-22',
    category: 'linux',
    level: 'middle',
    ua: 'З мережі різко зріс вихідний трафік на 25-й порт. Як, маючи доступ на гейтвей, виявити шкідника з внутрішньої мережі?',
    en: 'Outbound traffic on port 25 suddenly spiked. With gateway access, how do you find the offending host on the internal network?',
  },
  { id: 'm-linux-23', category: 'linux', level: 'middle', ua: 'Як затюнити параметри Linux Kernel?', en: 'How do you tune Linux kernel parameters?' },
  { id: 'm-linux-24', category: 'linux', level: 'middle', ua: 'Що таке ulimits?', en: 'What are ulimits?' },
  {
    id: 'm-linux-25',
    category: 'linux',
    level: 'middle',
    ua: 'У чому різниця між символічними та hard links?',
    en: "What's the difference between symbolic and hard links?",
  },
  { id: 'm-linux-26', category: 'linux', level: 'middle', ua: 'Що таке фрагментація ext3 and ext4?', en: 'What is ext3/ext4 fragmentation?' },
  {
    id: 'm-linux-27',
    category: 'linux',
    level: 'middle',
    ua: 'Навіщо файлові системи ext* резервують 5% місця?',
    en: 'Why do ext* filesystems reserve 5% of space?',
  },
  { id: 'm-linux-28', category: 'linux', level: 'middle', ua: 'Як збільшити розмір файлової системи?', en: "How do you grow a filesystem's size?" },
  { id: 'm-linux-29', category: 'linux', level: 'middle', ua: 'Чи можемо ми зменшити розмір файлової системи?', en: "Can we shrink a filesystem's size?" },
  { id: 'm-linux-30', category: 'linux', level: 'middle', ua: 'Що таке chroot і навіщо він потрібний?', en: 'What is chroot and why is it needed?' },
  {
    id: 'm-linux-31',
    category: 'linux',
    level: 'middle',
    ua: 'У нас є Linux box з 2 Гб оперативної пам\'яті та Java-застосунок, який намагається виділити 4 Гб під час запуску. Чи вдасться це?',
    en: 'We have a Linux box with 2GB RAM and a Java app that tries to allocate 4GB at startup. Will it succeed?',
  },
  {
    id: 'm-linux-32',
    category: 'linux',
    level: 'middle',
    ua: 'Є програма, яка читає файл, який користувач намагається видалити. Що трапиться? Чи можна видалити цей файл? Чи можна відновити цей файл?',
    en: "A program is reading a file that a user is trying to delete. What happens? Can this file be deleted? Can it be recovered?",
  },
  {
    id: 'm-linux-33',
    category: 'linux',
    level: 'middle',
    ua: 'Які механізми створення процесів у Linux ви знаєте?',
    en: 'What process-creation mechanisms in Linux do you know?',
  },
  { id: 'm-linux-34', category: 'linux', level: 'middle', ua: 'Порівняйте systemd та init system.', en: 'Compare systemd and the init system.' },
  {
    id: 'm-linux-35',
    category: 'linux',
    level: 'middle',
    ua: 'У вас є папка з великою кількістю файлів, і ви хочете видалити всі файли з іменами, що починаються на A (велика літера). Але команда rm -f A* видає Argument list too long. Як можна видалити ці файли?',
    en: 'You have a folder with many files and want to delete all files whose names start with capital "A", but `rm -f A*` fails with "Argument list too long." How do you delete these files?',
  },
  {
    id: 'm-linux-36',
    category: 'linux',
    level: 'middle',
    ua: 'Ви починаєте видаляти файли першим методом з попереднього питання, але кожен rm запитує підтвердження. Це дуже довго. Як можна прискорити цю операцію?',
    en: 'You start deleting files with the method from the previous question, but every `rm` asks for confirmation, which is very slow. How do you speed this up?',
  },
  {
    id: 'm-networks-37',
    category: 'networks',
    level: 'middle',
    ua: 'Розкажіть про модель OSI. Опишіть функції та призначення кожного рівня.',
    en: 'Describe the OSI model. Describe the function and purpose of each layer.',
  },
  {
    id: 'm-networks-38',
    category: 'networks',
    level: 'middle',
    ua: 'Які мережеві топології ви знаєте? Опишіть різницю між ними.',
    en: 'What network topologies do you know? Describe the difference between them.',
  },
  {
    id: 'm-networks-39',
    category: 'networks',
    level: 'middle',
    ua: 'Навіщо потрібна IP-адреса, якщо MAC-адреса унікальна? Хіба ми не можемо спілкуватися тільки за MAC-адресою?',
    en: "Why do we need an IP address if a MAC address is unique? Can't we communicate using only MAC addresses?",
  },
  {
    id: 'm-networks-40',
    category: 'networks',
    level: 'middle',
    ua: 'У чому різниця між концентратором і комутатором L2 у мережах Ethernet?',
    en: "What's the difference between an L2 hub and a switch in Ethernet networks?",
  },
  {
    id: 'm-networks-41',
    category: 'networks',
    level: 'middle',
    ua: 'Що таке Vlan і навіщо існує поділ на віртуальні локальні мережі?',
    en: 'What is a VLAN and why does the split into virtual LANs exist?',
  },
  {
    id: 'm-networks-42',
    category: 'networks',
    level: 'middle',
    ua: 'Який номер порту використовують для PING-комунікації?',
    en: 'What port number is used for PING communication?',
  },
  {
    id: 'm-networks-43',
    category: 'networks',
    level: 'middle',
    ua: 'Що таке сеанс зв\'язку? Який алгоритм використовує TCP для доставки?',
    en: 'What is a communication session? What algorithm does TCP use for delivery?',
  },
  {
    id: 'm-networks-44',
    category: 'networks',
    level: 'middle',
    ua: 'У чому основна відмінність між TCP і UDP?',
    en: "What's the main difference between TCP and UDP?",
  },
  { id: 'm-networks-45', category: 'networks', level: 'middle', ua: 'Навіщо нам маршрутизатор за замовчуванням?', en: 'Why do we need a default gateway?' },
  { id: 'm-networks-46', category: 'networks', level: 'middle', ua: 'Як хост вирішує DNS за замовчуванням?', en: 'How does a host resolve DNS by default?' },
  {
    id: 'm-networks-47',
    category: 'networks',
    level: 'middle',
    ua: 'Комп\'ютер почав отримувати IP-адресу з іншої мережі (є підозра, що в мережі працює інший DHCP-сервер): як його знайти і від\'єднати? Які є методи захисту від такої проблеми?',
    en: 'A computer started receiving an IP address from a different network (suspected rogue DHCP server): how do you find and disconnect it? What protections against this exist?',
  },
  {
    id: 'm-networks-48',
    category: 'networks',
    level: 'middle',
    ua: 'Ми будемо мігрувати сайт на нову IP-адресу. Як зробити, щоб користувачі цього практично не помітили?',
    en: "We're migrating a site to a new IP address. How do we make this practically unnoticeable to users?",
  },
  { id: 'm-networks-49', category: 'networks', level: 'middle', ua: 'Що таке socket?', en: 'What is a socket?' },
  {
    id: 'm-networks-50',
    category: 'networks',
    level: 'middle',
    ua: 'Як дізнатися, які віддалені хости під\'єднуються до хосту через порт 8888? (за допомогою команд і не використовуючи /proc чи /sys).',
    en: 'How do you find out which remote hosts are connecting to a host via port 8888 (using commands, without /proc or /sys)?',
  },
  {
    id: 'm-networks-51',
    category: 'networks',
    level: 'middle',
    ua: 'Ми маємо кілька мережевих карт. Як збільшити пропускну спроможність сервера?',
    en: 'We have several network cards. How do you increase server throughput?',
  },
  {
    id: 'm-networks-52',
    category: 'networks',
    level: 'middle',
    ua: 'Як перевірити відкриті порти на віддаленому сервері без команди Netcat чи Nmap Linux?',
    en: 'How do you check open ports on a remote server without Netcat or Nmap?',
  },
  {
    id: 'm-orchestration-53',
    category: 'orchestration',
    level: 'middle',
    ua: 'У чому переваги Kubernetes як платформи?',
    en: 'What are the advantages of Kubernetes as a platform?',
  },
  {
    id: 'm-orchestration-54',
    category: 'orchestration',
    level: 'middle',
    ua: 'Що таке control plane та з яких компонентів складається?',
    en: 'What is the control plane and what components does it consist of?',
  },
  {
    id: 'm-orchestration-55',
    category: 'orchestration',
    level: 'middle',
    ua: 'Які CNI ви використовували та чим вони відрізняються?',
    en: 'What CNIs have you used and how do they differ?',
  },
  {
    id: 'm-orchestration-56',
    category: 'orchestration',
    level: 'middle',
    ua: 'Чим відрізняється managed Kubernetes від self-deployed?',
    en: 'How does managed Kubernetes differ from self-deployed?',
  },
  {
    id: 'm-orchestration-57',
    category: 'orchestration',
    level: 'middle',
    ua: 'Яким чином можна контролювати розміщення подів у кластері? (taints/tolerations, affinities, topologies etc)',
    en: 'How can you control pod placement in a cluster? (taints/tolerations, affinities, topologies, etc.)',
  },
  {
    id: 'm-orchestration-58',
    category: 'orchestration',
    level: 'middle',
    ua: 'Скейлінг кластеру. Cluster autoscaler vs HPA vs VPA? Як зробити zero-downtime node decommission/cluster upgrade? PDB? Lifecycle hooks?',
    en: 'Cluster scaling: Cluster Autoscaler vs HPA vs VPA? How do you do a zero-downtime node decommission/cluster upgrade? PDB? Lifecycle hooks?',
  },
  {
    id: 'm-orchestration-59',
    category: 'orchestration',
    level: 'middle',
    ua: 'Які існують способи для зовнішнього доступу до кластеру? ingress, node port, port-forward тощо.',
    en: 'What ways exist for external access to a cluster? Ingress, NodePort, port-forward, etc.',
  },
  { id: 'm-orchestration-60', category: 'orchestration', level: 'middle', ua: 'З яким PID запускається процес у контейнері?', en: 'What PID does a process run with inside a container?' },
  {
    id: 'm-orchestration-61',
    category: 'orchestration',
    level: 'middle',
    ua: 'Що краще використовувати для ізоляції оточення — Vagrant чи Docker?',
    en: "What's better for environment isolation — Vagrant or Docker?",
  },
  {
    id: 'm-orchestration-62',
    category: 'orchestration',
    level: 'middle',
    ua: 'Який інструмент оркестрування контейнерів використовували? (Swarm, Kubernetes, Openshift, Rancher тощо.)',
    en: 'Which container orchestration tool have you used? (Swarm, Kubernetes, OpenShift, Rancher, etc.)',
  },
  {
    id: 'm-orchestration-63',
    category: 'orchestration',
    level: 'middle',
    ua: 'Що відбувається в Kubernetes після запуску kubectl (API, ReplicaSet Controller, storage back-end, scheduler, kubelet, worker node, pod)?',
    en: "What happens in Kubernetes after running `kubectl` (API, ReplicaSet controller, storage back-end, scheduler, kubelet, worker node, pod)?",
  },
  {
    id: 'm-orchestration-64',
    category: 'orchestration',
    level: 'middle',
    ua: 'Яка різниця між pod та контейнером у K8s?',
    en: "What's the difference between a pod and a container in K8s?",
  },
  {
    id: 'm-orchestration-65',
    category: 'orchestration',
    level: 'middle',
    ua: 'Як ми можемо зробити будь-який мікросервіс, який працює на K8s, доступним із зовнішнього середовища?',
    en: 'How can we make any microservice running on K8s accessible from outside?',
  },
  { id: 'm-virtualization-66', category: 'virtualization', level: 'middle', ua: 'Які типи віртуалізації ви знаєте?', en: 'What types of virtualization do you know?' },
  { id: 'm-virtualization-67', category: 'virtualization', level: 'middle', ua: 'Як працює Docker на macOS/Windows?', en: 'How does Docker work on macOS/Windows?' },
  {
    id: 'm-virtualization-68',
    category: 'virtualization',
    level: 'middle',
    ua: 'Що таке Docker-image і Docker-контейнер? Як вони між собою пов\'язані?',
    en: 'What is a Docker image and a Docker container? How are they related?',
  },
  {
    id: 'm-virtualization-69',
    category: 'virtualization',
    level: 'middle',
    ua: 'Які основні відмінності між контейнерами докерів і віртуальними машинами?',
    en: 'What are the main differences between Docker containers and virtual machines?',
  },
  {
    id: 'm-virtualization-70',
    category: 'virtualization',
    level: 'middle',
    ua: 'Що таке image layer? Яка максимальна кількість layers можлива? Чому треба намагатися мати малу кількість layers? Яка оптимальна кількість?',
    en: "What is an image layer? What's the max number of layers possible? Why should you try to keep few layers? What's the optimal number?",
  },
  {
    id: 'm-virtualization-71',
    category: 'virtualization',
    level: 'middle',
    ua: 'Як у віртуальній машині змінити розмір диска після створення? Що треба зробити з гостьовою ОС?',
    en: "How do you resize a VM's disk after creation? What must be done on the guest OS?",
  },
  {
    id: 'm-virtualization-72',
    category: 'virtualization',
    level: 'middle',
    ua: 'Як у Docker реалізовано обмеження ресурсів?',
    en: 'How are resource limits implemented in Docker?',
  },
  {
    id: 'm-virtualization-73',
    category: 'virtualization',
    level: 'middle',
    ua: 'Існує віртуальна машина, до якої втрачено доступ. Як, маючи доступ до її диска, відновити root пароль/SSH-ключ?',
    en: "There's a VM you've lost access to. With access to its disk, how do you recover the root password/SSH key?",
  },
  {
    id: 'm-virtualization-74',
    category: 'virtualization',
    level: 'middle',
    ua: 'Оптимізувати Dockerfile, пояснити, що і чому так:\nFROM golang\nRUN apt install -y pkg1 pkg2 pkgN # Dependencies for app\nCOPY . .\nRUN go build -o app main.go\nCMD ./app',
    en: 'Optimize this Dockerfile and explain what and why:\nFROM golang\nRUN apt install -y pkg1 pkg2 pkgN # Dependencies for app\nCOPY . .\nRUN go build -o app main.go\nCMD ./app',
  },
  { id: 'm-virtualization-75', category: 'virtualization', level: 'middle', ua: 'Що таке IPVS та який функціонал у нього є?', en: 'What is IPVS and what functionality does it have?' },
  { id: 'm-virtualization-76', category: 'virtualization', level: 'middle', ua: 'Яка структура API у Kubernetes?', en: 'What is the structure of the Kubernetes API?' },
  { id: 'm-virtualization-77', category: 'virtualization', level: 'middle', ua: 'Що таке operators і для чого вони потрібні?', en: 'What are operators and what are they for?' },
  {
    id: 'm-cicd-78',
    category: 'ci-cd',
    level: 'middle',
    ua: 'Які стадії мають бути в будь-якому пайплайні (lint, test, build, deploy etc)?',
    en: 'What stages should any pipeline have (lint, test, build, deploy, etc.)?',
  },
  { id: 'm-cicd-79', category: 'ci-cd', level: 'middle', ua: 'Як і де зберігати build artifacts?', en: 'How and where do you store build artifacts?' },
  { id: 'm-cicd-80', category: 'ci-cd', level: 'middle', ua: 'Що таке артефакт?', en: 'What is an artifact?' },
  {
    id: 'm-cicd-81',
    category: 'ci-cd',
    level: 'middle',
    ua: 'Є два бренчі: dev і stage. Ми закинули Dockerfile у dev, а потім збілдили у dev і stage. Це буде одним артефактом чи різними?',
    en: 'There are two branches: dev and stage. We added a Dockerfile in dev, then built it in dev and stage. Is that one artifact or different ones?',
  },
  {
    id: 'm-cicd-82',
    category: 'ci-cd',
    level: 'middle',
    ua: 'Що ви використовували для автоматизації налаштування Jenkins and GitLab CI?',
    en: 'What have you used to automate Jenkins and GitLab CI setup?',
  },
  {
    id: 'm-cicd-83',
    category: 'ci-cd',
    level: 'middle',
    ua: 'Порівняйте CI інструментів: Jenkins, GitLab CI, AWS Code Pipeline, GCP cloudbuild, GitHub actions, Circle CI.',
    en: 'Compare CI tools: Jenkins, GitLab CI, AWS CodePipeline, GCP Cloud Build, GitHub Actions, CircleCI.',
  },
  {
    id: 'm-cicd-84',
    category: 'ci-cd',
    level: 'middle',
    ua: 'Deployment strategies. Які існують і чим відрізняються (recreate, blue-green, canary etc)?',
    en: 'Deployment strategies. Which exist and how do they differ (recreate, blue-green, canary, etc.)?',
  },
  {
    id: 'm-cicd-85',
    category: 'ci-cd',
    level: 'middle',
    ua: 'Яким чином реалізувати СI/CD для програми, яка залежить від кількох інших програм?',
    en: 'How do you implement CI/CD for an app that depends on several other apps?',
  },
  { id: 'm-cicd-86', category: 'ci-cd', level: 'middle', ua: 'GitOps. В чому його переваги та недоліки?', en: 'GitOps. What are its advantages and disadvantages?' },
  {
    id: 'm-clouds-87',
    category: 'clouds',
    level: 'middle',
    ua: 'Яка роль і переваги хмарних сервісів для DevOps?',
    en: 'What is the role and benefit of cloud services for DevOps?',
  },
  {
    id: 'm-clouds-88',
    category: 'clouds',
    level: 'middle',
    ua: 'Що таке immutable infrastructure? Як досягти? У чому переваги та недоліки? Packer, AMI тощо.',
    en: 'What is immutable infrastructure? How do you achieve it? Pros and cons? Packer, AMI, etc.',
  },
  {
    id: 'm-clouds-89',
    category: 'clouds',
    level: 'middle',
    ua: 'Структура Terraform. Як організувати multi-environment project? Terraform workspaces?',
    en: 'Terraform structure. How do you organize a multi-environment project? Terraform workspaces?',
  },
  {
    id: 'm-clouds-90',
    category: 'clouds',
    level: 'middle',
    ua: 'Найкращі практики з використання багатьох Terraform states.',
    en: 'Best practices for working with multiple Terraform states.',
  },
  {
    id: 'm-clouds-91',
    category: 'clouds',
    level: 'middle',
    ua: 'Як організувати доступ розробницькій команді до AWS/GCP/Azure? Role-based access, assume role, SSO.',
    en: 'How do you organize a dev team\'s access to AWS/GCP/Azure? Role-based access, assume role, SSO.',
  },
  { id: 'm-clouds-92', category: 'clouds', level: 'middle', ua: 'Що таке Terraform provider, module?', en: 'What is a Terraform provider, a module?' },
  { id: 'm-clouds-93', category: 'clouds', level: 'middle', ua: 'Як версіонувати Terraform modules?', en: 'How do you version Terraform modules?' },
  {
    id: 'm-clouds-94',
    category: 'clouds',
    level: 'middle',
    ua: 'Коли потрібно використовувати local-exec та remote-exec?',
    en: 'When should you use local-exec vs remote-exec?',
  },
  { id: 'm-clouds-95', category: 'clouds', level: 'middle', ua: 'Що таке golden image та як його створити?', en: 'What is a golden image and how do you create one?' },
  {
    id: 'm-monitoring-96',
    category: 'monitoring',
    level: 'middle',
    ua: 'Як моніторинг допомагає підтримувати всю архітектуру системи?',
    en: 'How does monitoring help maintain an entire system architecture?',
  },
  { id: 'm-monitoring-97', category: 'monitoring', level: 'middle', ua: 'Які інструменти моніторингу ви використовували?', en: 'What monitoring tools have you used?' },
  { id: 'm-monitoring-98', category: 'monitoring', level: 'middle', ua: 'Що таке медіана та процентиль?', en: 'What is a median and a percentile?' },
  { id: 'm-monitoring-99', category: 'monitoring', level: 'middle', ua: 'Що таке SLI, SLO, SLA? Навіщо це потрібно?', en: 'What are SLI, SLO, SLA? Why are they needed?' },
  {
    id: 'm-monitoring-100',
    category: 'monitoring',
    level: 'middle',
    ua: 'Архітектура системи для збору логів, ELK, EFK etc. Як зберегти логи у разі відмови сховища? Чи потрібно використовувати для цього брокер повідомлень? Чи потрібно робити throttling/rate limits?',
    en: 'Architecture of a log-collection system: ELK, EFK, etc. How do you preserve logs if storage fails? Do you need a message broker for this? Do you need throttling/rate limits?',
  },
  { id: 'm-monitoring-101', category: 'monitoring', level: 'middle', ua: 'Prometheus long-term storage. Які варіанти?', en: 'Prometheus long-term storage. What options exist?' },
  { id: 'm-monitoring-102', category: 'monitoring', level: 'middle', ua: 'Як працює Prometheus?', en: 'How does Prometheus work?' },
  {
    id: 'm-monitoring-103',
    category: 'monitoring',
    level: 'middle',
    ua: 'У чому принципова відмінність між Grafana і Kibana?',
    en: "What's the fundamental difference between Grafana and Kibana?",
  },
  {
    id: 'm-monitoring-104',
    category: 'monitoring',
    level: 'middle',
    ua: 'В чому головна відмінність між Ansible and Terraform?',
    en: "What's the main difference between Ansible and Terraform?",
  },
  { id: 'm-monitoring-105', category: 'monitoring', level: 'middle', ua: 'Що таке SAAS monitoring та які види знаєте?', en: 'What is SaaS monitoring and what kinds do you know?' },
  {
    id: 'm-monitoring-106',
    category: 'monitoring',
    level: 'middle',
    ua: 'Якщо ви використовуєте Datadog/NewRelic, то як нам відстежувати падіння інструментів моніторингу?',
    en: 'If you use Datadog/New Relic, how do we track the monitoring tools themselves going down?',
  },
  {
    id: 'm-monitoring-107',
    category: 'monitoring',
    level: 'middle',
    ua: 'Що таке distributed tracing та error tracking systems? Як ви думаєте, коли варто їх використовувати?',
    en: 'What are distributed tracing and error-tracking systems? When do you think it is worth using them?',
  },
  {
    id: 'm-security-108',
    category: 'security',
    level: 'middle',
    ua: 'У чому різниця між RBAC та ABAC?',
    en: "What's the difference between RBAC and ABAC?",
  },
  {
    id: 'm-security-109',
    category: 'security',
    level: 'middle',
    ua: 'У чому полягає XSS атака? SQL injection? Що таке CSP?',
    en: 'What is an XSS attack? SQL injection? What is CSP?',
  },
  {
    id: 'm-security-110',
    category: 'security',
    level: 'middle',
    ua: 'Які базові заходи можна вжити для захисту SSH-з\'єднання?',
    en: 'What basic measures can you take to protect an SSH connection?',
  },
  {
    id: 'm-security-111',
    category: 'security',
    level: 'middle',
    ua: 'Root-пароль невідомий чи загублений. Яка процедура відновлення?',
    en: "The root password is unknown or lost. What's the recovery procedure?",
  },
  { id: 'm-security-112', category: 'security', level: 'middle', ua: 'Як керувати правами на файловій системі в Linux?', en: 'How do you manage filesystem permissions in Linux?' },
  { id: 'm-security-113', category: 'security', level: 'middle', ua: 'Що таке Firewall?', en: 'What is a Firewall?' },
  {
    id: 'm-security-114',
    category: 'security',
    level: 'middle',
    ua: 'Чим відрізняється stateless від stateful фаєрволів?',
    en: "What's the difference between stateless and stateful firewalls?",
  },
  { id: 'm-security-115', category: 'security', level: 'middle', ua: 'Скільки таблиць у iptables?', en: 'How many tables does iptables have?' },
  {
    id: 'm-security-116',
    category: 'security',
    level: 'middle',
    ua: 'Чи можна налаштувати трансляцію NAT за допомогою iptables? Яку таблицю варто використати?',
    en: 'Can NAT translation be configured with iptables? Which table should be used?',
  },
  {
    id: 'm-security-117',
    category: 'security',
    level: 'middle',
    ua: 'Яку таблицю використовують для зміни заголовків пакетів?',
    en: 'Which table is used to modify packet headers?',
  },
  {
    id: 'm-security-118',
    category: 'security',
    level: 'middle',
    ua: 'Якщо вам ламають Linux-сервер, то як більш ефективно блокувати трафік з IP-адрес?',
    en: 'If your Linux server is being attacked, how do you more effectively block traffic from IP addresses?',
  },
  {
    id: 'm-security-119',
    category: 'security',
    level: 'middle',
    ua: 'Принцип роботи GCP Firewall: чи можемо ми профільтрувати трафік на Load Balancer?',
    en: 'How does GCP Firewall work — can we filter traffic on a Load Balancer?',
  },
  { id: 'm-security-120', category: 'security', level: 'middle', ua: 'Що таке SELinux?', en: 'What is SELinux?' },
  { id: 'm-security-121', category: 'security', level: 'middle', ua: 'Чи можна повністю від\'єднати SELinux на льоту?', en: 'Can SELinux be fully disabled on the fly?' },
  { id: 'm-security-122', category: 'security', level: 'middle', ua: 'З якими secrets management systems ви працювали?', en: 'Which secrets management systems have you worked with?' },
  {
    id: 'm-security-123a',
    category: 'security',
    level: 'middle',
    ua: 'У нас є сервер NAT, і ми хочемо забезпечити доступ за ІР до сервера зовні. Як нам це реалізувати?',
    en: 'We have a NAT server and want to provide external IP-based access to it. How do we implement this?',
  },
  {
    id: 'm-security-123b',
    category: 'security',
    level: 'middle',
    ua: 'Щоб потрапити на сервер клієнта, треба залогінитись на 4+ jump хоста. Як це автоматизувати? Де ми зберігатимемо наш SSH-ключ?',
    en: "To reach a client's server you need to log in through 4+ jump hosts. How do you automate this? Where do we store our SSH key?",
  },
  { id: 'm-development-125', category: 'development', level: 'middle', ua: 'Що таке cookies? Для чого потрібні? JWT?', en: 'What are cookies? What are they for? JWT?' },
  {
    id: 'm-development-126',
    category: 'development',
    level: 'middle',
    ua: 'Що таке feature toggles та навіщо вони?',
    en: 'What are feature toggles and why are they used?',
  },
  {
    id: 'm-development-127',
    category: 'development',
    level: 'middle',
    ua: 'Що таке TDD (Test Driven Development) та BDD (Behaviour Driven Development)?',
    en: 'What are TDD (Test-Driven Development) and BDD (Behaviour-Driven Development)?',
  },
  { id: 'm-databases-128', category: 'databases', level: 'middle', ua: 'Що таке індекс і що таке ключ?', en: 'What is an index and what is a key?' },
  { id: 'm-databases-129', category: 'databases', level: 'middle', ua: 'Які переваги та недоліки індексів?', en: 'What are the pros and cons of indexes?' },
  {
    id: 'm-databases-130',
    category: 'databases',
    level: 'middle',
    ua: 'Уявіть, що ви розробляєте систему білінгу, яка має обробляти тисячі рахунків. Яку стратегію оновлення даних ви б обрали?',
    en: 'Imagine you are building a billing system that must process thousands of invoices. What data-update strategy would you choose?',
  },
  {
    id: 'm-databases-131',
    category: 'databases',
    level: 'middle',
    ua: 'Які методи найчастіше використовують для масштабування реляційних баз даних?',
    en: 'What methods are most commonly used to scale relational databases?',
  },
  { id: 'm-databases-132', category: 'databases', level: 'middle', ua: 'Опишіть механізм транзакцій БД.', en: 'Describe the database transaction mechanism.' },
  { id: 'm-databases-133', category: 'databases', level: 'middle', ua: 'Як ми можемо видалити таблицю чи базу даних?', en: 'How can we drop a table or a database?' },
  {
    id: 'm-databases-134',
    category: 'databases',
    level: 'middle',
    ua: 'Як знайти повільні запити у MySQL/PostgreSQL?',
    en: 'How do you find slow queries in MySQL/PostgreSQL?',
  },
  {
    id: 'm-databases-135',
    category: 'databases',
    level: 'middle',
    ua: 'Які SQL-оператори маніпулювання даними ви знаєте?',
    en: 'What SQL data-manipulation statements do you know?',
  },
  {
    id: 'm-databases-136',
    category: 'databases',
    level: 'middle',
    ua: 'Чи можна вивести список баз даних/таблиць через CLI? Як ми можемо перемикатися між базами даних MySQL/PostgreSQL?',
    en: 'Can you list databases/tables via CLI? How do you switch between MySQL/PostgreSQL databases?',
  },
  {
    id: 'm-databases-137',
    category: 'databases',
    level: 'middle',
    ua: 'Які storage engines в MySQL ви знаєте? Які відмінності?',
    en: 'What MySQL storage engines do you know? What are the differences?',
  },
  {
    id: 'm-databases-138',
    category: 'databases',
    level: 'middle',
    ua: 'Як реалізовано реплікацію MySQL master-master? Скільки серверів MySQL може бути залучено в такій взаємодії?',
    en: 'How is MySQL master-master replication implemented? How many MySQL servers can be involved in such a setup?',
  },
  {
    id: 'm-databases-139',
    category: 'databases',
    level: 'middle',
    ua: 'Як працює реплікація MySQL/PostgreSQL? Які параметри мають бути налаштовані для реплікації?',
    en: 'How does MySQL/PostgreSQL replication work? What parameters must be configured for replication?',
  },
  { id: 'm-databases-140', category: 'databases', level: 'middle', ua: 'Порівняйте SQL і NoSQL.', en: 'Compare SQL and NoSQL.' },
  { id: 'm-databases-141', category: 'databases', level: 'middle', ua: 'Sharding vs replication?', en: 'Sharding vs replication?' },
  {
    id: 'm-databases-142',
    category: 'databases',
    level: 'middle',
    ua: 'Які є види індексів? Коли і для чого використовувати?',
    en: 'What kinds of indexes exist? When and why do you use them?',
  },
  {
    id: 'm-databases-143',
    category: 'databases',
    level: 'middle',
    ua: 'Вимоги до схеми БД. Character sets, collations, default, not null тощо.',
    en: 'Requirements for a DB schema. Character sets, collations, default, not null, etc.',
  },
  {
    id: 'm-databases-144',
    category: 'databases',
    level: 'middle',
    ua: 'Ми мігруємо MySQL/PostgreSQL з on-prem у хмару. Як нам зробити це з мінімальним даунтаймом?',
    en: 'We are migrating MySQL/PostgreSQL from on-prem to the cloud. How do we do this with minimal downtime?',
  },
  {
    id: 'm-databases-145',
    category: 'databases',
    level: 'middle',
    ua: 'Навіщо та як тестувати перформанс баз даних?',
    en: 'Why and how do you test database performance?',
  },
  {
    id: 'm-practical-146',
    category: 'practical',
    level: 'middle',
    ua: 'Напишіть Terraform module для інфраструктури тестового сервісу у AWS.',
    en: "Write a Terraform module for a test service's infrastructure in AWS.",
  },
  {
    id: 'm-practical-147',
    category: 'practical',
    level: 'middle',
    ua: 'Напишіть hello-world програму мовою на ваш вибір і сформуйте для неї helm chart/kustomize.',
    en: 'Write a hello-world program in a language of your choice and create a Helm chart/Kustomize config for it.',
  },
  { id: 'm-practical-148', category: 'practical', level: 'middle', ua: 'Як організувати деплой без downtime?', en: 'How do you organize a deployment without downtime?' },
  {
    id: 'm-practical-149',
    category: 'practical',
    level: 'middle',
    ua: 'Опишіть способи troubleshooting для Docker-контейнера.',
    en: 'Describe troubleshooting approaches for a Docker container.',
  },
  {
    id: 'm-practical-150',
    category: 'practical',
    level: 'middle',
    ua: 'Розібрати і пояснити структуру CI/CD pipeline (на прикладі gitlab.yml).',
    en: 'Break down and explain a CI/CD pipeline structure (using a gitlab.yml example).',
  },
  {
    id: 'm-practical-151',
    category: 'practical',
    level: 'middle',
    ua: 'Продемонструйте навички роботи з GitOps, опишіть деплоймент простенької програми.',
    en: 'Demonstrate GitOps skills — describe deploying a simple app.',
  },
  {
    id: 'm-practical-152',
    category: 'practical',
    level: 'middle',
    ua: 'Як організувати деплой вебзастосунку, запущений на кількох серверах без (або з мінімальним) downtime?',
    en: 'How do you organize deploying a web app running on multiple servers with no (or minimal) downtime?',
  },
  {
    id: 'm-practical-153',
    category: 'practical',
    level: 'middle',
    ua: 'Як за допомогою Ansible дізнатися default gateway для пулу серверів, і якщо він відрізняється від бажаного, записати рядок «hostname: gateway» у файл на локальній машині?',
    en: 'Using Ansible, how do you find the default gateway for a pool of servers, and if it differs from the desired one, write a "hostname: gateway" line to a file on the local machine?',
  },
]

// CTO (Expert) — all Senior-level questions.
export const CTO_QUESTIONS: BankQuestion[] = [
  {
    id: 's-linux-1',
    category: 'linux',
    level: 'senior',
    ua: 'Що може створювати високе навантаження на CPU (процеси застосунків споживають дуже мало ресурсів CPU)?',
    en: 'What can cause high CPU load when application processes consume very little CPU themselves?',
  },
  {
    id: 's-linux-2',
    category: 'linux',
    level: 'senior',
    ua: 'У нас немає команд ifconfig, ip, і поставити ми їх не можемо. Як нам дізнатися ip address, mask, network, routes?',
    en: "We don't have the ifconfig/ip commands and can't install them. How do we find the IP address, mask, network, and routes?",
  },
  { id: 's-linux-3', category: 'linux', level: 'senior', ua: 'Що таке suid, sgid та sticky?', en: 'What are suid, sgid, and the sticky bit?' },
  {
    id: 's-linux-4',
    category: 'linux',
    level: 'senior',
    ua: 'Що тюнилося з системою для навантаження трафіку 1GB, 10G, 40G+?',
    en: 'What system tuning is needed for 1GB, 10G, 40G+ traffic loads?',
  },
  {
    id: 's-linux-5',
    category: 'linux',
    level: 'senior',
    ua: 'Що тюнилося з системою для високого навантаження на диск?',
    en: 'What system tuning is needed for high disk load?',
  },
  { id: 's-linux-6', category: 'linux', level: 'senior', ua: 'Що таке Linux namespaces?', en: 'What are Linux namespaces?' },
  { id: 's-linux-7', category: 'linux', level: 'senior', ua: 'Що таке Ceph, як працює?', en: 'What is Ceph, and how does it work?' },
  { id: 's-linux-8', category: 'linux', level: 'senior', ua: 'Що потрібно тюнити для Ceph?', en: 'What needs to be tuned for Ceph?' },
  {
    id: 's-linux-9',
    category: 'linux',
    level: 'senior',
    ua: 'Що станеться, якщо /dev/sda1 перенесемо в /root?',
    en: 'What happens if we move /dev/sda1 into /root?',
  },
  {
    id: 's-linux-10',
    category: 'linux',
    level: 'senior',
    ua: 'Ми видалили /dev/sda1. Як нам його відновити? Що таке pseudo-devices?',
    en: 'We deleted /dev/sda1. How do we recover it? What are pseudo-devices?',
  },
  {
    id: 's-linux-11',
    category: 'linux',
    level: 'senior',
    ua: 'Нам хакнули сервер, і в директорії /var/www створили два мільйони файлів невеликого розміру. Якщо використовувати команду cd /var/www і потім rm -rf*, то у нас зависне термінал. Як видалити файли?',
    en: 'Our server was hacked, and two million small files were created in /var/www. Running `cd /var/www` then `rm -rf *` hangs the terminal. How do we delete the files?',
  },
  { id: 's-linux-12', category: 'linux', level: 'senior', ua: 'На якому рівні працює iptables?', en: 'At what layer does iptables operate?' },
  { id: 's-linux-13', category: 'linux', level: 'senior', ua: 'Що таке eBPF та навіщо потрібен?', en: 'What is eBPF and why is it needed?' },
  {
    id: 's-linux-14',
    category: 'linux',
    level: 'senior',
    ua: 'У вас є файл, який містить IP-адреси серверів (по одному в рядку). Є SSH-доступ до цих машин, і вам потрібно виконати завдання (наприклад, встановити список пакетів на всі вузли). Поясніть, як це можна зробити.',
    en: 'You have a file containing server IP addresses (one per line). You have SSH access to these machines and need to perform a task (e.g. install a list of packages on all nodes). Explain how to do this.',
  },
  {
    id: 's-networking-15',
    category: 'networks',
    level: 'senior',
    ua: 'У чому відмінності між IPv4 та IPv6? Навіщо ми мігруємо на IPv6?',
    en: 'What are the differences between IPv4 and IPv6? Why are we migrating to IPv6?',
  },
  {
    id: 's-networking-16',
    category: 'networks',
    level: 'senior',
    ua: 'Співіснування IPv4 та IPv6: що це означає?',
    en: 'IPv4/IPv6 coexistence: what does it mean?',
  },
  {
    id: 's-networking-17',
    category: 'networks',
    level: 'senior',
    ua: 'Чи справді працюють міжмережеві екрани з підтримкою IPv6?',
    en: 'Do firewalls really support IPv6 properly?',
  },
  {
    id: 's-networking-18',
    category: 'networks',
    level: 'senior',
    ua: 'Як працює DHCPv6? Чим він відрізняється від DHCPv4?',
    en: 'How does DHCPv6 work? How does it differ from DHCPv4?',
  },
  {
    id: 's-networking-19',
    category: 'networks',
    level: 'senior',
    ua: 'Як фрагментуються пакети IPv6 і чим це відрізняється від IPv4?',
    en: 'How are IPv6 packets fragmented, and how does this differ from IPv4?',
  },
  { id: 's-networking-20', category: 'networks', level: 'senior', ua: 'Чи з IPv6 треба більше використовувати NAT?', en: 'Do we need to use NAT more with IPv6?' },
  { id: 's-networking-21', category: 'networks', level: 'senior', ua: 'Що таке DPDK?', en: 'What is DPDK?' },
  {
    id: 's-networking-22',
    category: 'networks',
    level: 'senior',
    ua: 'Що таке SR-IOV? У чому різниця між DPDK та SR-IOV?',
    en: "What is SR-IOV? What's the difference between DPDK and SR-IOV?",
  },
  { id: 's-networking-23', category: 'networks', level: 'senior', ua: 'Що таке NetFlow та навіщо потрібен?', en: 'What is NetFlow and why is it needed?' },
  { id: 's-networking-24', category: 'networks', level: 'senior', ua: 'Що таке OpenFlow?', en: 'What is OpenFlow?' },
  {
    id: 's-networking-25',
    category: 'networks',
    level: 'senior',
    ua: 'Що таке SDN і які контролери ви знаєте? Порівняйте контролери.',
    en: 'What is SDN and which controllers do you know? Compare the controllers.',
  },
  { id: 's-misc-26', category: 'misc', level: 'senior', ua: 'Що таке SDLC?', en: 'What is SDLC?' },
  {
    id: 's-misc-27',
    category: 'misc',
    level: 'senior',
    ua: 'Розкажіть про останній досвід реалізації архітектури для сервісу.',
    en: 'Tell us about your most recent experience designing an architecture for a service.',
  },
  { id: 's-misc-28', category: 'misc', level: 'senior', ua: 'Який найважчий скрипт писали?', en: "What's the hardest script you've written?" },
  {
    id: 's-misc-29',
    category: 'misc',
    level: 'senior',
    ua: 'Що таке configuration drift? Чому це відбувається і як це ускладнює життя інженерам\\SRE\\Ops?',
    en: 'What is configuration drift? Why does it happen, and how does it complicate life for engineers/SRE/Ops?',
  },
  {
    id: 's-misc-30',
    category: 'misc',
    level: 'senior',
    ua: 'Розкажіть про архітектуру, за яку ви наразі відповідаєте, і вкажіть, як вона масштабована та відмовостійка.',
    en: "Tell us about the architecture you currently own, and how it's scaled and made fault-tolerant.",
  },
  { id: 's-misc-31', category: 'misc', level: 'senior', ua: 'Назвіть три важливі KPI для DevOps-фахівця.', en: 'Name three important KPIs for a DevOps professional.' },
  {
    id: 's-misc-32',
    category: 'misc',
    level: 'senior',
    ua: 'Як працює Kafka (clusters(brokers, controllers), topics, partitions)?',
    en: 'How does Kafka work (clusters (brokers, controllers), topics, partitions)?',
  },
  { id: 's-misc-33', category: 'misc', level: 'senior', ua: 'GitOps: Rancher Fleet vs Flux vs Argo?', en: 'GitOps: Rancher Fleet vs Flux vs Argo?' },
  {
    id: 's-misc-34',
    category: 'misc',
    level: 'senior',
    ua: 'Як використовувати GitOps для оновлення документації DevOps-застосунків?',
    en: 'How would you use GitOps to update documentation for DevOps applications?',
  },
  {
    id: 's-misc-35',
    category: 'misc',
    level: 'senior',
    ua: 'Розкажіть про особливості проєктування Kubernetes on-premise.',
    en: 'Tell us about the specifics of designing Kubernetes on-premise.',
  },
  { id: 's-misc-36', category: 'misc', level: 'senior', ua: 'Як організувати On-call процес для команди DevOps?', en: 'How do you organize an on-call process for a DevOps team?' },
  {
    id: 's-misc-37',
    category: 'misc',
    level: 'senior',
    ua: 'Опишіть основні кроки завантаження операційної системи Linux.',
    en: 'Describe the main steps of the Linux OS boot process.',
  },
  { id: 's-orchestration-38', category: 'orchestration', level: 'senior', ua: 'Service mesh. Що це таке та для чого потрібно?', en: 'Service mesh. What is it and what is it for?' },
  {
    id: 's-orchestration-39',
    category: 'orchestration',
    level: 'senior',
    ua: 'Cluster federation. Що це таке та для чого потрібно?',
    en: 'Cluster federation. What is it and what is it for?',
  },
  {
    id: 's-orchestration-40',
    category: 'orchestration',
    level: 'senior',
    ua: 'Pod fine-grained access. Як реалізувати? IRSA vs kube2iam vs kiam?',
    en: 'Pod fine-grained access. How do you implement it? IRSA vs kube2iam vs kiam?',
  },
  { id: 's-orchestration-41', category: 'orchestration', level: 'senior', ua: 'Як реалізовані послуги в кубернетах?', en: 'How are services implemented in Kubernetes?' },
  { id: 's-orchestration-42', category: 'orchestration', level: 'senior', ua: 'Як дебажити трафік контейнера?', en: 'How do you debug container traffic?' },
  { id: 's-orchestration-43', category: 'orchestration', level: 'senior', ua: 'Що таке unikernel і навіщо він потрібний?', en: 'What is a unikernel and why is it needed?' },
  {
    id: 's-orchestration-44',
    category: 'orchestration',
    level: 'senior',
    ua: 'Чому ком\'юніті переїжджає з Docker containerd?',
    en: 'Why is the community moving away from Docker to containerd?',
  },
  { id: 's-clouds-45', category: 'clouds', level: 'senior', ua: 'Які переваги і недоліки cloud-провайдерів?', en: 'What are the pros and cons of cloud providers?' },
  {
    id: 's-clouds-46',
    category: 'clouds',
    level: 'senior',
    ua: 'Cost optimization. Які є інструменти? Spot/preemptible instances, reservations?',
    en: 'Cost optimization. What tools exist? Spot/preemptible instances, reservations?',
  },
  {
    id: 's-clouds-47',
    category: 'clouds',
    level: 'senior',
    ua: 'Як організувати multi-account, multi-region cloud setup?',
    en: 'How do you organize a multi-account, multi-region cloud setup?',
  },
  {
    id: 's-clouds-48',
    category: 'clouds',
    level: 'senior',
    ua: 'У чому полягає різниця між приватними та публічними мережами в AWS?',
    en: "What's the difference between private and public networks in AWS?",
  },
  { id: 's-clouds-49', category: 'clouds', level: 'senior', ua: 'AWS Lambda: чи мали досвід роботи?', en: 'AWS Lambda: do you have experience working with it?' },
  {
    id: 's-clouds-50',
    category: 'clouds',
    level: 'senior',
    ua: 'Коли варто переходити на AWS Lambda? Коли не варто? Аналогічні рішення в GCP чи Kubernetes?',
    en: 'When should you move to AWS Lambda? When should you not? Similar solutions in GCP or Kubernetes?',
  },
  {
    id: 's-clouds-51',
    category: 'clouds',
    level: 'senior',
    ua: 'Коли краще використовувати CloudFormation, а коли Terraform?',
    en: 'When is it better to use CloudFormation vs Terraform?',
  },
  { id: 's-cicd-52', category: 'ci-cd', level: 'senior', ua: 'Що таке state в контексті використання Terraform?', en: 'What is "state" in the context of Terraform?' },
  {
    id: 's-cicd-53',
    category: 'ci-cd',
    level: 'senior',
    ua: 'Які існують branching strategy? На що опиратись при виборі?',
    en: 'What branching strategies exist? What should you base your choice on?',
  },
  { id: 's-cicd-54', category: 'ci-cd', level: 'senior', ua: 'Яким чином реалізувати feature/dynamic environments?', en: 'How do you implement feature/dynamic environments?' },
  {
    id: 's-cicd-55',
    category: 'ci-cd',
    level: 'senior',
    ua: 'Як зробити емуляцію ресурсів cloud-провайдера для локального тестування та прискорення розробки?',
    en: 'How do you emulate cloud-provider resources for local testing and faster development?',
  },
  { id: 's-cicd-56', category: 'ci-cd', level: 'senior', ua: 'Що таке MultiCloud?', en: 'What is MultiCloud?' },
  { id: 's-cicd-57', category: 'ci-cd', level: 'senior', ua: 'Що таке Cloud-Agnostic і коли він буде потрібний?', en: 'What is Cloud-Agnostic and when is it needed?' },
  {
    id: 's-cicd-58',
    category: 'ci-cd',
    level: 'senior',
    ua: 'Що таке Hybrid-Cloud та з якими рішеннями ви працювали?',
    en: 'What is Hybrid-Cloud, and which solutions have you worked with?',
  },
  {
    id: 's-security-59',
    category: 'security',
    level: 'senior',
    ua: 'Як мають зберігатися паролі в базах даних (Salt&Pepper, Rainbow Tables, Adaptive Hashing)?',
    en: 'How should passwords be stored in databases (Salt & Pepper, Rainbow Tables, Adaptive Hashing)?',
  },
  {
    id: 's-security-60',
    category: 'security',
    level: 'senior',
    ua: 'Як передавати секрети в application (Secrets management)?',
    en: 'How do you pass secrets into an application (secrets management)?',
  },
  { id: 's-security-61', category: 'security', level: 'senior', ua: 'Порівняйте CI/CD SAST та DAST?', en: 'Compare CI/CD SAST and DAST.' },
  {
    id: 's-security-62',
    category: 'security',
    level: 'senior',
    ua: 'Які ви знаєте Kubernetes security practices? RBAC? OPA? Які недоліки RBAC та які кейси знаєте?',
    en: "What Kubernetes security practices do you know? RBAC? OPA? What are RBAC's drawbacks, and what cases do you know?",
  },
  { id: 's-security-63', category: 'security', level: 'senior', ua: 'Розкажіть про захист від DDOS атак, WAF.', en: 'Tell us about DDoS protection, WAF.' },
  { id: 's-security-64', category: 'security', level: 'senior', ua: 'Що таке Rootless containers і навіщо він потрібний?', en: 'What are rootless containers and why are they needed?' },
  {
    id: 's-security-65',
    category: 'security',
    level: 'senior',
    ua: 'Що таке AppArmor та Seccomp і навіщо вони потрібні?',
    en: 'What are AppArmor and Seccomp, and why are they needed?',
  },
  {
    id: 's-security-66',
    category: 'security',
    level: 'senior',
    ua: 'Чи доводилося працювати з Falco? Якщо так, то що реалізовували?',
    en: 'Have you worked with Falco? If so, what did you implement?',
  },
  {
    id: 's-security-67',
    category: 'security',
    level: 'senior',
    ua: 'HashiCorp Vault і як правильно передати нам секрети в контейнер і CI pipeline?',
    en: 'HashiCorp Vault — how do you properly pass secrets into a container and a CI pipeline?',
  },
  { id: 's-security-68', category: 'security', level: 'senior', ua: 'Що таке Admission Controllers та які ви використовували?', en: 'What are Admission Controllers, and which have you used?' },
  {
    id: 's-security-69',
    category: 'security',
    level: 'senior',
    ua: 'Як зберігаються секрети etcd? Як переглянути ресурси в etcd?',
    en: 'How are secrets stored in etcd? How do you view resources in etcd?',
  },
  { id: 's-security-70', category: 'security', level: 'senior', ua: 'Чим перевіряєте на вразливості ваш Kubernetes cluster?', en: 'What do you use to check your Kubernetes cluster for vulnerabilities?' },
  { id: 's-security-71', category: 'security', level: 'senior', ua: 'Що таке Secure SDLC?', en: 'What is Secure SDLC?' },
  {
    id: 's-security-72',
    category: 'security',
    level: 'senior',
    ua: 'Що ви знаєте про Cloud Infrastructure Attack via a Pull Request і як цього уникнути?',
    en: 'What do you know about a Cloud Infrastructure Attack via a Pull Request, and how do you avoid it?',
  },
  {
    id: 's-observability-73',
    category: 'observability',
    level: 'senior',
    ua: 'Що таке observability та чим відрізняється від звичайного моніторингу? Які особливості необхідно враховувати у мікросервісній архітектурі (tracing)?',
    en: 'What is observability and how does it differ from regular monitoring? What specifics must be considered in a microservice architecture (tracing)?',
  },
  {
    id: 's-observability-74',
    category: 'observability',
    level: 'senior',
    ua: 'Що таке SLI, SLO, SLA та для чого вони потрібні? Навіщо використовують error budget?',
    en: 'What are SLI, SLO, SLA, and what are they for? Why use an error budget?',
  },
  { id: 's-databases-75', category: 'databases', level: 'senior', ua: 'Що таке теорема CAP? Навіщо це треба?', en: 'What is the CAP theorem? Why is it needed?' },
  {
    id: 's-databases-76',
    category: 'databases',
    level: 'senior',
    ua: 'Як працювати з міграціями? Що робити у випадку rollback? Як перевірити, що міграція backward-compatible?',
    en: 'How do you work with migrations? What do you do in case of a rollback? How do you verify a migration is backward-compatible?',
  },
  {
    id: 's-databases-77',
    category: 'databases',
    level: 'senior',
    ua: 'Опишіть, як би ви оптимізовували роботу бази данних? (БД за вибором кандидата) Slow queries, buffers, thread pools?',
    en: 'Describe how you would optimize database performance (candidate\'s choice of DB). Slow queries, buffers, thread pools?',
  },
  {
    id: 's-databases-78',
    category: 'databases',
    level: 'senior',
    ua: 'Навіщо потрібно тестувати перформанс бази даних та якими інструментами?',
    en: 'Why do you need to test database performance, and with what tools?',
  },
  {
    id: 's-practical-79',
    category: 'practical',
    level: 'senior',
    ua: 'Уявіть, що ви CTO Booking чи Airbnb. Які б ви ухвалювали рішення щодо: мови програмування, Infrastructure as a Code, архітектури інфраструктури, налаштування CI/CD?',
    en: "Imagine you're the CTO of Booking or Airbnb. What decisions would you make about: programming language, Infrastructure as Code, infrastructure architecture, CI/CD setup?",
  },
  {
    id: 's-practical-80',
    category: 'practical',
    level: 'senior',
    ua: 'У вас є файл, який містить патчі в директорії. Наприклад: /var/tmp/temp/file1.c, /var/tmp/file.ext, /var/tmp/temp/ тощо — один шлях у рядку. Якщо шлях закінчується на \'/\', це шлях до каталогу. Вам потрібно відновити це дерево каталогів із порожніми файлами в іншій файловій системі. Напишіть bash-скрипт.',
    en: "You have a file listing paths in a directory, e.g. /var/tmp/temp/file1.c, /var/tmp/file.ext, /var/tmp/temp/, etc — one path per line. If a path ends with '/', it's a directory. Recreate this directory tree with empty files on another filesystem. Write a bash script.",
  },
  {
    id: 's-practical-81',
    category: 'practical',
    level: 'senior',
    ua: 'Уявіть, що вам треба переконати Spotify, що використовує AWS, перейти на GCP. Як ви мотивуєте Spotify мігрувати на GCP?',
    en: 'Imagine you need to convince Spotify, which uses AWS, to move to GCP. How would you motivate Spotify to migrate to GCP?',
  },
  {
    id: 's-practical-82',
    category: 'practical',
    level: 'senior',
    ua: 'Є сервісна компанія, яка надає сервіс трекінгу перевезень. Є клієнти, які не хочуть, щоб їхні дані процесувалися в AWS. Як нам реалізувати multi-cloud solution?',
    en: "There's a service company providing a shipment-tracking service. Some clients don't want their data processed in AWS. How do we implement a multi-cloud solution?",
  },
]

export const QUESTION_BANKS: Record<string, BankQuestion[]> = {
  recruiter: RECRUITER_QUESTIONS,
  hr: HR_QUESTIONS,
  'senior-devops': SENIOR_DEVOPS_QUESTIONS,
  cto: CTO_QUESTIONS,
}
